# .github/release-drafter.yml

# Configuration for Release Drafter: https://github.com/release-drafter/release-drafter

# Name of the next release.
# The '$NEXT_PATCH_VERSION' variable will be automatically replaced with the next patch version number (e.g., v1.2.1).
# You can also use '$NEXT_MINOR_VERSION' or '$NEXT_MAJOR_VERSION'.
name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"

# Categories for changes. These are matched against the labels on your Pull Requests.
categories:
  - title: "🚀 New Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bug"
  - title: "📚 Documentation"
    labels:
      - "docs"
      - "documentation"
  - title: "🧹 Maintenance"
    labels:
      - "chore"
      - "refactor"
      - "ci"

# Template for the release notes body.
# '$CHANGES' will be replaced with the categorized list of Pull Requests.
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$NEXT_PATCH_VERSION
