name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.23.x

    - name: Build binaries
      run: |
        # Build binaries using Makefile
        make release
        
        # Create archives
        cd dist
        tar -czf flow-linux-amd64.tar.gz flow-linux-amd64
        tar -czf flow-linux-arm64.tar.gz flow-linux-arm64
        tar -czf flow-darwin-amd64.tar.gz flow-darwin-amd64
        tar -czf flow-darwin-arm64.tar.gz flow-darwin-arm64
        zip flow-windows-amd64.zip flow-windows-amd64.exe

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
        files: |
          dist/*.tar.gz
          dist/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN || secrets.GITHUB_TOKEN }} 